### ISSUE TITLE
到底怎么用啊 一直报空指针异常

### ISSUE THREAD

**Issue by davichi11** [Shonminh/go-orm-code-helper#21]
一直报这个错 我的版本是2020.2 

java.lang.NullPointerException
	at org.shonminh.helper.sql.SqlParser.parseStatements(SqlParser.java:64)
	at org.shonminh.helper.sql.SqlParser.Execute(SqlParser.java:90)
	at org.shonminh.helper.GenerateModelAction.actionPerformed(GenerateModelAction.java:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:519)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:541)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Shonminh** [comment]
麻烦提供一下create sql语句，正常情况下都是语法的问题。

**Comment by davichi11** [comment]
create table hrms_abroad_certificate
(
    id          int auto_increment primary key,
    emp_id      int          not null comment '员工id',
    name        varchar(50)  not null comment '证件名称',
    number      varchar(50)  null comment '证件编号',
    issue_date  datetime     null comment '发证日期',
    valid_date  datetime     null comment '证件有效期截止日期',
    save_org    varchar(150) null comment '保管机构',
    save_status tinyint      null comment '保管状态 0 未入库 1 入库 2 借出',
    create_by   varchar(50)  null,
    create_time datetime     null,
    update_by   varchar(50)  null,
    update_time datetime     null
)
    comment '因私出国境证件信息表';  这个有问题吗？

**Comment by davichi11** [comment]
`create table hrms_abroad_certificate
(
    id          int auto_increment primary key,
    emp_id      int          not null comment '员工id',
    name        varchar(50)  not null comment '证件名称',
    number      varchar(50)  null comment '证件编号',
    issue_date  datetime     null comment '发证日期',
    valid_date  datetime     null comment '证件有效期截止日期',
    save_org    varchar(150) null comment '保管机构',
    save_status tinyint      null comment '保管状态 0 未入库 1 入库 2 借出',
    create_by   varchar(50)  null,
    create_time datetime     null,
    update_by   varchar(50)  null,
    update_time datetime     null
)
    comment '因私出国境证件信息表';`

**Comment by Shonminh** [comment]
```sql
create table hrms_abroad_certificate
(
    id          int auto_increment,
    emp_id      int          not null comment '员工id',
    name        varchar(50)  not null comment '证件名称',
    number      varchar(50)  null comment '证件编号',
    issue_date  datetime     null comment '发证日期',
    valid_date  datetime     null comment '证件有效期截止日期',
    save_org    varchar(150) null comment '保管机构',
    save_status tinyint      null comment '保管状态 0 未入库 1 入库 2 借出',
    create_by   varchar(50)  null,
    create_time datetime     null,
    update_by   varchar(50)  null,
    update_time datetime     null,
    PRIMARY KEY (id)
) comment '因私出国境证件信息表';
```
@davichi11 请使用这样的格式，目前使用的库只支持这种格式的
